#!/usr/bin/env sh

if [ "x$1" = "x" ]; then
    echo "Usage: $0 <command> [args|opts]"
    exit 2
fi

echo "$@"
# NB: use the following fmt to keep space-separated arg together
"$@"
echo "exit code: $?"
